kind: Service
apiVersion: v1
metadata:
  name: nginx-np 
spec:
  type: NodePort
  selector:
    project: expense
    module: frontend
    component: frontend
    environment: dev
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
