apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-dynamic-claim
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-dynamic-sc
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: efs-dyn-app
  labels:
    purpose: efs-dynamic
spec:
  containers:
    - name: app
      image: nginx
      volumeMounts:
        - name: persistent-storage
          mountPath: /usr/share/nginx/html
  volumes:
    - name: persistent-storage
      persistentVolumeClaim:
        claimName: efs-dynamic-claim
---
apiVersion: v1
kind: Service
metadata:
  name: efs-dyn-service
spec:
  selector:
    purpose: efs-dynamic
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80